const ERROR_WRONG_DATA_CODE = 400;
const ERROR_NOT_FOUND_CODE = 404;
const ERROR_DEFAULT_CODE = 500;

const ERROR_DEFAULT_MESSAGE = 'Server was broken';

const VALIDATION_ERROR_NAME = 'ValidationError';

module.exports = {
  ERROR_WRONG_DATA_CODE,
  ERROR_NOT_FOUND_CODE,
  ERROR_DEFAULT_CODE,
  ERROR_DEFAULT_MESSAGE,
  VALIDATION_ERROR_NAME,
};
